# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2
      - name: 🚧 Build
        uses: valtyr/pandoc-action@v0.1-alpha
      - name: 🏛 Copy
        run: mkdir dist && cp *.pdf dist/
      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      # - name: Markdown to PDF
      #   uses: valtyr/pandoc-action@v0.1-alpha
      # - name: Pandoc generator - satzung.md
      #   uses: Lothindir/pandoc-markdown-action@v0.4
      #   with:
      #     markdown: "satzung.md"
      #     pdf: "satzung"
      #     template: "kate,monochrome"    
      # - name: Pandoc generator - beitragsordnung.md
      #   uses: Lothindir/pandoc-markdown-action@v0.4
      #   with:
      #     markdown: "beitragsordnung.md"
      #     pdf: "beitragsordnung"
      #     template: "kate,monochrome"    
      # - name: Pandoc generator - ehrenordnung.md
      #   uses: Lothindir/pandoc-markdown-action@v0.4
      #   with:
      #     markdown: "ehrenordnung.md"
      #     pdf: "ehrenordnung"
      #     template: "kate,monochrome"    
      # - name: Pandoc generator - finanzordnung.md
      #   uses: Lothindir/pandoc-markdown-action@v0.4
      #   with:
      #     markdown: "finanzordnung.md"
      #     pdf: "finanzordnung"
      #     template: "kate,monochrome"    
      # - name: Pandoc generator - jugendordnung.md
      #   uses: Lothindir/pandoc-markdown-action@v0.4
      #   with:
      #     markdown: "jugendordnung.md"
      #     pdf: "jugendordnung"
      #     template: "kate,monochrome"
